<?php
/**
 * GenZ Time - Main Site Header Component
 */

require_once __DIR__ . '/../config/site.php';
require_once __DIR__ . '/logo.php';
require_once __DIR__ . '/seo-helper.php';
require_once __DIR__ . '/db-helper.php';

$pageTitle = $pageTitle ?? (SITE_NAME . ' — ' . SITE_TAGLINE);
$pageDesc  = $pageDescription ?? SITE_DESCRIPTION;
$pageCanon = $pageCanonical ?? (BASE_URL . $_SERVER['REQUEST_URI']);
$pageImg   = $pageImage ?? 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1400&q=80';
$activeNav = $activeNav ?? 'home';

$metaConfig = [
    'title'       => $pageTitle,
    'description' => $pageDesc,
    'canonical'   => $pageCanon,
    'image'       => $pageImg,
    'keywords'    => $pageKeywords ?? null,
    'type'        => $pageType ?? 'website'
];

$categoriesList = db_get_categories();
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- SEO & Social Meta Generated by GenZ Time SEO Engine -->
  <?= seo_render_meta($metaConfig) ?>

  <!-- Font Awesome & Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  
  <!-- Main Cyber-Tech Stylesheet -->
  <link rel="stylesheet" href="<?= asset('assets/css/style.css') ?>">

  <!-- Schema.org WebSite & Org Structured Data -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebSite",
        "@id": "<?= BASE_URL ?>/#website",
        "url": "<?= BASE_URL ?>/",
        "name": "<?= addslashes(SITE_NAME) ?>",
        "description": "<?= addslashes(SITE_TAGLINE) ?>",
        "potentialAction": {
          "@type": "SearchAction",
          "target": "<?= BASE_URL ?>/blog.php?search={search_term_string}",
          "query-input": "required name=search_term_string"
        }
      },
      {
        "@type": "Organization",
        "@id": "<?= BASE_URL ?>/#organization",
        "name": "<?= addslashes(SITE_NAME) ?>",
        "url": "<?= BASE_URL ?>/",
        "logo": "<?= BASE_URL ?>/assets/images/logo.png",
        "sameAs": [
          "<?= SITE_TWITTER ?>",
          "<?= SITE_YOUTUBE ?>"
        ]
      }
    ]
  }
  </script>
</head>
<body>

  <!-- Top Trending Lab Ticker -->
  <div class="ticker-bar">
    <div class="container ticker-inner">
      <span class="ticker-label">LAB DISPATCH</span>
      <span class="ticker-text">
        ⚡ <strong>Live Benchmarks:</strong> Apple Vision Pro 2 Dual M4 Silicon • Samsung Galaxy S25 Ultra 200MP Periscope • M4 Max 128GB Memory Bandwidth • Asus ROG Ally X 80Wh Battery Run • Rabbit r2 AI Agent
      </span>
    </div>
  </div>

  <!-- Main Navigation Header -->
  <header class="site-header">
    <div class="container nav-inner">
      <!-- Cyber Logo -->
      <?= render_logo('md', true, true) ?>

      <!-- Desktop Links -->
      <ul class="nav-links">
        <li><a href="<?= url('/') ?>" class="nav-link <?= $activeNav === 'home' ? 'active' : '' ?>">Home</a></li>
        <li><a href="<?= url('blog.php') ?>" class="nav-link <?= $activeNav === 'reviews' ? 'active' : '' ?>">Hardware Reviews</a></li>
        <li><a href="<?= url('category.php?slug=smartphones') ?>" class="nav-link <?= $activeNav === 'smartphones' ? 'active' : '' ?>">Smartphones</a></li>
        <li><a href="<?= url('category.php?slug=laptops-computing') ?>" class="nav-link <?= $activeNav === 'laptops' ? 'active' : '' ?>">Laptops</a></li>
        <li><a href="<?= url('category.php?slug=vr-wearables') ?>" class="nav-link <?= $activeNav === 'vr' ? 'active' : '' ?>">Spatial & VR</a></li>
        <li><a href="<?= url('about.php') ?>" class="nav-link <?= $activeNav === 'about' ? 'active' : '' ?>">Testing Lab (E-E-A-T)</a></li>
        <li><a href="<?= url('contact.php') ?>" class="nav-link <?= $activeNav === 'contact' ? 'active' : '' ?>">Contact</a></li>
      </ul>

      <!-- Action Buttons -->
      <div class="nav-actions">
        <a href="<?= url('blog.php') ?>" class="btn btn-secondary btn-sm" title="Search hardware database">
          <i class="fa-solid fa-magnifying-glass"></i> Search
        </a>
        <a href="<?= url('admin/index.php') ?>" class="btn btn-cyber btn-sm" title="Admin CMS Portal">
          <i class="fa-solid fa-lock"></i> Admin CMS
        </a>
      </div>
    </div>
  </header>

  <main>
